[build]
  publish = "docs"

[[redirects]]
  from = "/api/trigger-scan"
  to = "/.netlify/functions/trigger-scan"
  status = 200

[[redirects]]
  from = "/api/run"
  to = "/.netlify/functions/trigger-scan"
  status = 200
